### ISSUE TITLE
Add support to wait for database to be available before running migrate

### ISSUE THREAD

**Issue by hectcastro** [azavea/azavea.g8#11]
When using the `update` script, check to ensure the database is available before attempting to execute `migrate`.

**Comment by rbreslow** [comment]
I'd consider the seeing what the approach taken with [`wait-for-postgres.sh`](https://docs.docker.com/compose/startup-order/) would look like. Maybe we could add it in a `update.d` directory?

 It doesn't particularly spark joy, but especially if we'd ever like to use the 3.0 Compose file format, we'll need to adopt something like this eventually.

**Comment by pomadchin** [comment]
Replaved via https://github.com/azavea/azavea.g8/issues/29
