### ISSUE TITLE
Upgrade to Scala 2.12.12

### ISSUE THREAD

**Issue by jisantuc** [azavea/azavea.g8#12]
By default, the `application` project uses Scala 2.12.11. The latest scala 2.12 is 2.12.12. It's valuable to stay current because it makes our eventual upgrade path to 2.13 / Scala 3 easier (with 2.13 as a bridge that will include many backports).

What breaks in 2.12.12 is plugin versions mainly.

**Comment by pomadchin** [comment]
Resolved in terms of https://github.com/azavea/azavea.g8/pull/14/files#diff-bdf4be1e160ac540d916cd47fa4d0d759f2dc081bf268e9505637e55c1090c6eR68
