### ISSUE TITLE
Consider alternative method of accepting application configuration

### ISSUE THREAD

**Issue by hectcastro** [azavea/azavea.g8#19]
Currently, it appears as though we're making use of `decline` to accept command line arguments to configure the application (e.g., `--db-port`). For target environments like Amazon ECS, we've historically supplied application configuration via environment variables (or overwritten settings defaults from a `application.conf` file via the environment). Maintaining support for that pattern is valuable because it has worked well, aligns with other project types, and allows for additional task definition flexibility.

**Comment by jisantuc** [comment]
We learned how to do this a while after starting the template but never backported 😨 thanks for the issue!
