### ISSUE TITLE
Use OrganizeImports scalafix action for organizing imports

### ISSUE THREAD

**Issue by jisantuc** [azavea/azavea.g8#37]
This scalafix plugin adds configurable import organization that works very nicely (including removing unused!): https://github.com/liancheng/scalafix-organize-imports

Also, it works with Metals, so it has a nice integration with VSCode, vim, and emacs: https://scalameta.org/metals/docs/editors/overview.html#editor-support

**Comment by ColeKettler** [comment]
@jisantuc Is this distinct from the changes introduced in #27?

**Comment by jisantuc** [comment]
Ha! I thought it sounded familiar. I searched "OrganizeImports" in the repo rather than `organize-imports` though.
